# codecov.yml
codecov:
  token: 0053b45f-32fd-4628-b1b1-1676fb31459c

coverage:
  status:
    project:
      default:
        # Set a threshold for overall coverage
        target: 80%
    patch:
      default:
        # Set a threshold for new code introduced by a pull request
        target: 80%

# Ignore specific files or directories
ignore:
  - "tests/*"
  - "node_modules/*"

# Notifications can be configured for pull requests, status changes, etc.
comment:
  layout: "header, diff, flags, files"
  behavior: default

# Set the maximum number of files to show in the report
range: 40

# Adjust how Codecov calculates coverage reports
coverage:
  precision: 2
  round: down
  range: "70...100"
